apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
  labels:
    app: login-application
spec:
  replicas: 2
  selector:
    matchLabels:
      name: app-pod
      app: login-application
  template:
    metadata:
      name: application
      labels:
        name: app-pod
        app: login-application
    spec:
      containers:
      - name: login-app
        image: arjunvyadav/myapp:tagVersion
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
